fix issue #1064
elebumm/RedditVideoMakerBot pull request #1065
Opened 2022-07-23 16:02 UTC by joshgreenwood2003

# Description

now will process text when text is split for TTS, *before* checking if the end of the split text is empty

# Issue Fixes

fixes #1064 

None

# Checklist:

- [ X] I am pushing changes to the **develop** branch
- [ X] I am using the recommended development environment
- [ X] I have performed a self-review of my own code
- [ X] I have commented my code, particularly in hard-to-understand areas
- [X ] I have formatted and linted my code using python-black and pylint
- [X ] I have cleaned up unnecessary files
- [X ] My changes generate no new warnings
- [X ] My changes follow the existing code-style
- [X] My changes are relevant to the project

# Any other information (e.g how to test the changes)

None

2022-07-23 18:06 UTC, JasonLovesDoggo requested changes
This is kind of inefficient as you are calling it three times now

Can you just create a new variable with the processed text and use that instead

2022-07-23 22:36 UTC, joshgreenwood2003 commented
added requested changes

2022-07-23 23:06 UTC, JasonLovesDoggo commented on TTS/engine_wrapper.py
> +            text, filepath=f"{self.path}/{filename}.mp3"
Why did you just remove the process text call

2022-07-24 15:28 UTC, JasonLovesDoggo approved these changes

2022-07-24 15:28 UTC, merged