Feature: Pyttsx
elebumm/RedditVideoMakerBot pull request #1092
Opened 2022-07-29 17:02 UTC by Supreme-hub

# Description
Allows the user to use Pyttsx for TTS.

# Issue Fixes

#1063 

# Checklist:

- [x] I am pushing changes to the **develop** branch
- [x] I am using the recommended development environment
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have formatted and linted my code using python-black and pylint
- [x] I have cleaned up unnecessary files
- [x] My changes generate no new warnings
- [x] My changes follow the existing code-style
- [x] My changes are relevant to the project

# Any other information (e.g how to test the changes)

None

2022-07-29 17:02 UTC, Supreme-hub commented
Hey, I changed the branch name, so it closed the PR.

2022-07-29 18:05 UTC, CallumIO requested changes
Please format your files using black

You have changed every file for a simple addition

2022-07-29 18:11 UTC, Supreme-hub commented
Hey, black made those changes, not me

2022-07-29 18:41 UTC, Supreme-hub commented
I have done the changes you asked

2022-07-29 18:48 UTC, Supreme-hub commented
@CallumIO

2022-07-29 19:18 UTC, JasonLovesDoggo requested changes

2022-07-29 19:18 UTC, JasonLovesDoggo commented on utils/.config.template.toml
> +voice_choice = { optional = false, default = "", options = ["streamlabspolly", "tiktok", "googletranslate", "awspolly", "pyttsx"], example = "tiktok", explanation = "The voice platform used for TTS g
Add back the trailing comma

2022-07-30 00:52 UTC, Supreme-hub commented
Added back trailing commas

2022-07-30 02:04 UTC, JasonLovesDoggo approved these changes

2022-07-30 02:04 UTC, merged