3 util functions for main so the ui looks nicer and 1 bug fix
elebumm/RedditVideoMakerBot pull request #1172
Opened 2022-08-17 18:35 UTC by notcooler

# Description

i added 3 util functions in the main file. getPlatform(), setConsoleSize(), and clear()

getPlatform returns a string according to the platform.
setConsoleSize sets console size by the following x and y values. used in the begin so the banner looks nicer :)
clear() called before banner prints so it also looks more nicer. 👍 

# Issue Fixes
There was one issue if the user was using python 3.9 or above and that was that match stament wasnt used anymore in subreddit.py line 44, so changed it to a simple understandable if line. Hope it helps!

# Checklist:

- [ y] I am pushing changes to the **develop** branch
- [y ] I am using the recommended development environment
- [ y] I have performed a self-review of my own code
- [ y] I have commented my code, particularly in hard-to-understand areas
- [ y] I have formatted and linted my code using python-black and pylint
- [ y] I have cleaned up unnecessary files
- [ y] My changes generate no new warnings
- [y ] My changes follow the existing code-style
- [y ] My changes are relevant to the project

# Any other information (e.g how to test the changes)
Hope i sent enough info. ;)
run and see the changes

2022-08-17 18:56 UTC, StopmotionSimonYT commented
Looks good! But can you remove the fix of the match statement? It is already fixed in the develop branch and now it is causing merge conflicts.

2022-08-19 14:07 UTC, AcidClown approved these changes

2022-08-19 18:12 UTC, notcooler commented
all done is it good now?

2022-08-19 18:39 UTC, StopmotionSimonYT commented
It has still merge conflicts, can you figure out what it is? I can also copy your pull request and fix it (ofcourse give you the credit).

2022-08-20 07:32 UTC, notcooler commented
fixed it now

2022-08-20 07:33 UTC, notcooler commented
it says i merged develop to master, but i didnt do idk what that is

2022-08-20 07:35 UTC, StopmotionSimonYT commented
> it says i merged develop to master, but i didnt do idk what that is

You synchronized the branches. Now it works! @JasonLovesDoggo or @callumio can it be merged?

2022-08-20 15:54 UTC, JasonLovesDoggo commented
> > it says i merged develop to master, but i didnt do idk what that is
> 
> You synchronized the branches. Now it works! @JasonLovesDoggo or @callumio can it be merged?

I will leave it to Callum

2022-08-24 18:06 UTC, notcooler commented
Is callum busy or... why isnt he responding

2022-08-24 20:16 UTC, StopmotionSimonYT approved these changes

2022-08-25 19:52 UTC, StopmotionSimonYT commented
> Is Callum busy or... why isn't he responding?

Due to personal circumstances, he is not responding

2022-08-26 00:21 UTC, JasonLovesDoggo commented
> > Is Callum busy or... why isn't he responding?
> 
> Due to personal circumstances, he is not responding

@StopmotionSimonYT did you actually test it to see it looks fine or just review the code..

2022-08-26 06:43 UTC, StopmotionSimonYT commented
> > > Is Callum busy or... why isn't he responding?
> > 
> > Due to personal circumstances, he is not responding
> 
> @StopmotionSimonYT did you actually test it to see it looks fine or just review the code.. 

I just reviewed the code but I could test it if you want.

2022-08-26 12:14 UTC, StopmotionSimonYT commented
> > > @StopmotionSimonYT did you actually test it to see it looks fine or just review the code.. 
> > 
> > I just reviewed the code but I could test it if you want.
> 
> Its simple tho i think you get it by just looking at it- althougj test it if you want

Yes the code looks good to me! But can you move the defs to the utils folder and import them in main.py? If that's done I would test it and it could be merged.

2022-08-26 13:51 UTC, notcooler commented
it should work now. although @StopmotionSimonYT you gotta test it on windows tho since idk if putted the column and line values at the good place for windows.

2022-08-26 14:19 UTC, StopmotionSimonYT requested changes

2022-08-26 14:28 UTC, StopmotionSimonYT commented
The resize resolution is not good on Windows
![image](https://user-images.githubusercontent.com/65854503/186927020-698641d7-92e0-4207-a364-77ff32e085d5.png)

2022-09-08 08:36 UTC, notcooler commented on main.py
> +    "### Thanks for using this tool! [Feel free to contribute to this project on GitHub!](https://lewismenelaws.com) If you have any questions, feel free to reach out to me on Twitter or submit a Git
I didnt do that tho

2022-09-08 08:37 UTC, notcooler commented
Anyways i decided to just cancel this rewuest since you guys are developing a gui system as well so i dont really want to work on this anymore. But thanks for all the help. :)

PS - Also sorry i was on vacation i couldnt use github for a while

2022-09-08 08:40 UTC, closed without merging