Creating_a_thumbnail
elebumm/RedditVideoMakerBot pull request #1296
Opened 2022-10-12 03:56 UTC by JvSdv

# Description
Create a thumbnail for the video using the PRAW library.

- thumbnail : Need to put the thumbnail.png image in the assets/backgrounds folder.
- font_family : The font family to use for the title.
- font_size : The font size to use for the title.
- font_color : The font color to use for the title.
- width,height : The width of the thumbnail is based on the thumbnail image.

1. Thumbnail created takes the image of the assets and writes the title post on top of this image.
2. The thumbnail is then saved in the assets/{id}/temp folder.
3. And finally the thumbnail is saved in the results/{subreddit}/thumbnails folder.

# Issue Fixes
None

# Checklist:

- [x] I am pushing changes to the **develop** branch
- [x] I am using the recommended development environment
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have formatted and linted my code using python-black and pylint
- [x] I have cleaned up unnecessary files
- [x] My changes generate no new warnings
- [x] My changes follow the existing code-style
- [x] My changes are relevant to the project

# Any other information (e.g how to test the changes)
Thanks for the bot helps me bring good content to Brazil

2022-10-12 13:02 UTC, JvSdv commented
Put any image in assets/backgrounds folder
![thumbnail_large](https://user-images.githubusercontent.com/100035055/195348976-1a23d39c-9a8c-4cfc-9d7d-49bfac499b04.png)
![thumbnail_shorts](https://user-images.githubusercontent.com/100035055/195348979-192d6790-9a4b-4148-964d-5d76cd7f29ba.png)

2022-10-14 18:04 UTC, OpenSourceSimon reviewed
Looks good to me, haven't tested it though.

2022-10-14 18:04 UTC, OpenSourceSimon approved these changes

2022-10-14 18:15 UTC, JasonLovesDoggo commented
I would just change this to drop an image in the folder and it will use that as the background

2022-10-14 18:16 UTC, JasonLovesDoggo requested changes
See above comment

2022-10-14 18:18 UTC, OpenSourceSimon commented
> I would just change this to drop an image in the folder and it will use that as the background 

That's possible if you put a thumbnail.png in the assets/backgrounds/ folder. Or do you mean something else?

2022-10-15 14:58 UTC, JvSdv commented
That's right. maybe change the name to background.png or something else?

2022-10-15 15:00 UTC, OpenSourceSimon commented
> That's right. maybe change the name to background.png or something else?
> 
> 

I think it shouldn't be in the assets folder since it's only for media generated by the bot. Maybe utils?

2022-12-18 07:53 UTC, JasonLovesDoggo requested changes

2022-12-18 07:53 UTC, JasonLovesDoggo commented on utils/.config.template.toml
Explain that it's a rgb color

2022-12-18 07:53 UTC, JasonLovesDoggo commented on video_creation/final_video.py
> -    filename = f"{name_normalize(title)[:251]}.mp4"
Why.... 251 was specific..

2022-12-18 07:54 UTC, JasonLovesDoggo commented
> > That's right. maybe change the name to background.png or something else?
> > 
> > 
> 
> I think it shouldn't be in the assets folder since it's only for media generated by the bot. Maybe utils?

This is generated by the bot though??

2022-12-18 07:57 UTC, OpenSourceSimon commented
> > > That's right. maybe change the name to background.png or something else?
> > > 
> > > 
> > 
> > I think it shouldn't be in the assets folder since it's only for media generated by the bot. Maybe utils?
> 
> This is generated by the bot though?? 

Sorry for not being clear. I was talking about the input background image. The assets folder is mostly for temp files and can be easily removed for bug fixing. The end thumbnail will go at the results folder if I remember correctly. 

But now there are more PRs with customization and they're using the assets folder too so we'll keep it also in this PR.

2022-12-18 07:59 UTC, JasonLovesDoggo commented
> > > > That's right. maybe change the name to background.png or something else?
> > > > 
> > > > 
> > > 
> > > I think it shouldn't be in the assets folder since it's only for media generated by the bot. Maybe utils?
> > 
> > This is generated by the bot though?? 
> 
> Sorry for not being clear. I was talking about the input background image. The assets folder is mostly for temp files and can be easily removed for bug fixing. The end thumbnail will go at the results folder if I remember correctly. 
> 
> But now there are more PRs with customization and they're using the assets folder too so we'll keep it also in this PR.

From what I understand about this MR, the background image is generated by the bot and yeah it should definitely end up in results if it's going to be an output

2022-12-19 15:37 UTC, OpenSourceSimon approved these changes
Tested and looks good! Thank you for your PR!

2022-12-19 15:37 UTC, OpenSourceSimon commented on video_creation/final_video.py
> +    filename = f"{name_normalize(title)[:150]}"
```suggestion
    filename = f"{name_normalize(title)[:251]}"
```
On suggestion of Jason, 251 as a limit was specifically chosen.

2022-12-19 18:18 UTC, merged