File name will now be name of the question.
elebumm/RedditVideoMakerBot pull request #139
Opened 2022-06-02 12:10 UTC by Kamushy

Wanted to do this because it makes it easier if producing mutliple videos. Please let me know of any errors

2022-06-02 13:10 UTC, JasonLovesDoggo commented
LGTM!

2022-06-02 13:39 UTC, hitesh3132 commented
it does work

2022-06-02 14:28 UTC, Proton45 commented
What would happen if the program chooses the same thread a second time? Would it just overwrite the file or would it break? Either way, it would be very good if the programm would just skip a thread that it has already been turned into a video. I thought of this, but I'm not sure how to implement it

2022-06-02 23:02 UTC, Kamushy commented
> > What would happen if the program chooses the same thread a second time? Would it just overwrite the file or would it break? Either way, it would be very good if the program would just skip a thread that it has already been turned into a video. I thought of this, but I'm not sure how to implement it
> 
> already implemented in my fork
> 
> see [this commit](https://github.com/JasonLovesDoggo/RedditVideoMakerBot/commit/8b5670a8ebe17e8fa4f2bac00cb7ae2d40d5b290)

Is this an issue with my code, or the code as a whole?

2022-06-02 23:32 UTC, Proton45 commented
> > > What would happen if the program chooses the same thread a second time? Would it just overwrite the file or would it break? Either way, it would be very good if the program would just skip a thread that it has already been turned into a video. I thought of this, but I'm not sure how to implement it
> > 
> > 
> > already implemented in my fork
> > see [this commit](https://github.com/JasonLovesDoggo/RedditVideoMakerBot/commit/8b5670a8ebe17e8fa4f2bac00cb7ae2d40d5b290)
> 
> Is this an issue with my code, or the code as a whole?

Nope. It was just a question I had. Your code works great!

2022-06-03 01:21 UTC, Kamushy commented
#167

2022-06-03 01:26 UTC, Kamushy commented
Could somebody fix the conflicts, I'm at school currently and won't be able to fix it within 24 hours. @JasonLovesDoggo

2022-06-03 01:32 UTC, JasonLovesDoggo commented
> What would happen if the program chooses the same thread a second time? Would it just overwrite the file or would it break? Either way, it would be very good if the programm would just skip a thread that it has already been turned into a video. I thought of this, but I'm not sure how to implement it

Sorry I'm at a friend's house and I won't be home until early tomorrow.

2022-06-03 02:11 UTC, Kamushy commented
Resolved conflict

2022-06-03 05:41 UTC, jacesleeman commented
should def be pushed into the master works well and so helpful

2022-06-03 17:05 UTC, CallumIO requested changes
Looks good, just needs a few tweaks to fit with the new file structure and module names.

2022-06-03 17:05 UTC, CallumIO commented on reddit/subreddit.py
> +def get_askreddit_threads():
Please change back to `get_subreddit_threads()` as that is the new method

2022-06-03 17:05 UTC, CallumIO commented on video_creation/final_video.py
> +import reddit.askreddit
Should import `reddit.subreddit` to fit new file name

2022-06-03 17:05 UTC, CallumIO commented on video_creation/final_video.py
> +    filename = (re.sub('[?\"%*:|<>]', '', ("assets/" + reddit.askreddit.submission.title + ".mp4")))
Needs to be changed to new filename

2022-06-04 01:06 UTC, Kamushy commented
> Looks good, just needs a few tweaks to fit with the new file structure and module names.

Changes should be fixed now

2022-06-04 01:19 UTC, CallumIO approved these changes
LGTM!
Thanks for this 😄

2022-06-04 04:55 UTC, jacesleeman approved these changes

2022-06-04 22:39 UTC, merged

2022-06-04 22:39 UTC, CallumIO commented
Thanks for this 😃