Acronyms
elebumm/RedditVideoMakerBot pull request #1627
Opened 2023-05-08 14:53 UTC by Tal-Dahann

# Description

Added `utils\acronyms.json` It's very minimal, but users are free to add their own (and its stated when configuring the setting)
Added `replace_ancronyms` setting, default is set to False. Setting to true will replace all the acronyms with full words.
Changed the `engine_wrapper.py` to replace the ancronyms if the setting is set to True, right after adding periods

# Issue Fixes

Not an issue but a feature, related to issue #1254 

# Checklist:

- [X] I am pushing changes to the **develop** branch
- [X] I am using the recommended development environment
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have formatted and linted my code using python-black and pylint
- [X] I have cleaned up unnecessary files
- [X] My changes generate no new warnings
- [X] My changes follow the existing code-style
- [X] My changes are relevant to the project

# Any other information (e.g how to test the changes)

None

> Note: This is my first PR so hopefully i didn't mess something up 

.

2023-05-08 15:06 UTC, OpenSourceSimon approved these changes

2023-05-13 00:43 UTC, liamb13 commented
Please take another look at this, I did a boiled down test and found it has the potential for some unexpected results:

```
import re

string = "imo: imogen does not understand multimolecular chemistry."
if re.search("imo", string):
    string = string.replace("imo", "in my opinion")
print(string)
```

The expected result of this is:
in my opinion: imogen does not understand multimolecular chemistry.

The actual result is:
in my opinion: in my opiniongen does not understand multin my opinionlecular chemistry.

2023-05-16 06:17 UTC, electro199 reviewed
Need redesign

2023-05-16 06:17 UTC, electro199 commented on TTS/engine_wrapper.py
> +
don't do it like that dont place your code in wrapper instead do it process text functon

2023-05-16 06:17 UTC, electro199 commented on utils/acronyms.json
> +}
dont put curse word

2023-05-19 19:51 UTC, OpenSourceSimon requested changes
See comments from others

2023-05-26 10:58 UTC, closed without merging

2023-07-18 17:38 UTC, KingCaliph commented
Did this ever get fully finished? I add the necessary code but ran into errors. I changed and added code where it seemed needed, and it did seem to fix certain initial errors, but I just kept running into more problems. Was this idea closed because people got bored with it, or is there some issue on my part?

2023-07-18 17:57 UTC, OpenSourceSimon commented
It was closed because it has too much issues