fixed screenshots bug
elebumm/RedditVideoMakerBot pull request #1648
Opened 2023-05-18 23:51 UTC by MohamedBechirMejri

# Description

can't take screenshots on the new reddit design. this is a temporary fix for it thanks to @SpaYco 

# Issue Fixes

#1647 

None

# Checklist:

- [ ] I am pushing changes to the **develop** branch
- [ ] I am using the recommended development environment
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have formatted and linted my code using python-black and pylint
- [ ] I have cleaned up unnecessary files
- [ ] My changes generate no new warnings
- [ ] My changes follow the existing code-style
- [ ] My changes are relevant to the project

# Any other information (e.g how to test the changes)

None

2023-05-20 05:27 UTC, electro199 requested changes
need changes

2023-05-20 05:27 UTC, electro199 commented on video_creation/screenshot_downloader.py
> +                    ).screenshot(path=f"assets/temp/{reddit_id}/png/comment_{idx}.png")
It will only work in non logged in state

2023-05-24 01:24 UTC, liamb13 commented
I've also attempted to fix the issue here: https://github.com/elebumm/RedditVideoMakerBot/pull/1663

I personally think the redesign looks better for the videos, so my approach removes the opt-out cookie

2023-05-28 11:36 UTC, OpenSourceSimon commented
#1663 is a better fix

2023-05-28 11:36 UTC, closed without merging