allow a custom background to be used instead of the Minecraft parkour
elebumm/RedditVideoMakerBot pull request #171
Opened 2022-06-02 21:31 UTC by reoccurcat

Another edit lol, this time it's checking off one of the to-dos.
This commit is allowing a custom video background in place of the Minecraft parkour video. It also makes a couple of UI adjustments to keep up with the other commits done previously. The clips, instead of being named "background", are named off of their YouTube video ID (the parts following `?v=`, such as `n_Dv4JMiwK8`).

2022-06-03 05:50 UTC, jacesleeman commented
instead of putting the url in background.py should be in .env or ask

2022-06-03 16:54 UTC, reoccurcat commented
fixed conflicts

2022-06-03 18:33 UTC, CallumIO requested changes
Looks good, just need you to fix the spelling error.
Also could you remove the 'AskReddit' reference on line 34 of subreddit.py?

2022-06-03 18:33 UTC, CallumIO commented on reddit/subreddit.py
> +    print_step("Getting subbreddit threads...")
Spelling: Subreddit not Subbreddit

2022-06-03 18:35 UTC, reoccurcat commented on reddit/subreddit.py
> +    print_step("Getting subbreddit threads...")
fixed!

2022-06-03 18:36 UTC, reoccurcat commented
fixed the issues

2022-06-05 18:23 UTC, reoccurcat commented
fixed conflicts again

2022-06-06 03:38 UTC, reoccurcat commented
@CallumIO should be fixed now

2022-06-07 18:13 UTC, ProjectSlxsh commented
Uploading WhatAreyouScaredof.mp4…
choped down so it fits githubs size requirements

2022-06-07 18:14 UTC, ProjectSlxsh commented
https://user-images.githubusercontent.com/93690295/172453553-ab6b7d77-735f-4fda-85d3-f79ea8b1f359.mp4

cut down to 15-20 seconds to meet githubs size requirements

2022-06-07 18:16 UTC, reoccurcat commented
It does that but saving the background using different file names each time so it doesn't get overwritten

2022-06-07 18:36 UTC, ProjectSlxsh commented
ah I see, i dont understand what you did but, ok

2022-06-07 18:37 UTC, ProjectSlxsh commented
also I know this is unrelated, but I did see that in the changes it mentioned changing the voice, how is this accomplished?

2022-06-08 17:03 UTC, reoccurcat commented
at this point, I feel this pull request is being ignored. If no progress is made in another few days, I'll close it.

2022-06-08 18:07 UTC, CallumIO approved these changes
Sorry, it's not being ignored I've just been busy and we were waiting for a new release before any more big PR's - looks good though and thank you for this!

2022-06-08 18:07 UTC, merged

2022-06-08 18:08 UTC, reoccurcat commented
Oh thank you!