updated readme for improved installation
elebumm/RedditVideoMakerBot pull request #2093
Opened 2024-07-14 18:52 UTC by DraKen0009

# Issue Fixes
#2068 

# Checklist:

- [x] I am pushing changes to the **develop** branch
- [ ] I am using the recommended development environment
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have formatted and linted my code using python-black and pylint
- [x] I have cleaned up unnecessary files
- [ ] My changes generate no new warnings
- [x] My changes follow the existing code-style
- [x] My changes are relevant to the project

# Any other information (e.g how to test the changes)

None

2024-07-14 19:12 UTC, JasonLovesDoggo requested changes

2024-07-14 19:12 UTC, JasonLovesDoggo commented on README.md
> +        source venv/bin/activate
Maybe just switch those to ./venv

2024-07-14 19:21 UTC, DraKen0009 commented
@JasonLovesDoggo  looks good now ?

2024-07-15 01:40 UTC, JasonLovesDoggo approved these changes
LGTM

2024-07-15 01:40 UTC, merged