Allowing users to choose a reddit thread instead of being randomized
elebumm/RedditVideoMakerBot pull request #238
Opened 2022-06-03 21:45 UTC by DomizianoScarcelli

Added a new .env variable that allows the user to insert a thread link

If the user inserts a thread link, it will be used to make the video, otherwise, the thread will be randomized as the previous version.

2022-06-03 21:47 UTC, DomizianoScarcelli commented
Closes issues #237

2022-06-03 22:24 UTC, 5vl commented
Hi, I'm not someone who is a reviewer or anything, but you might want to add .idea/ and .DS_STORE to the .gitignore

2022-06-03 23:10 UTC, DomizianoScarcelli commented
> Hi, I'm not someone who is a reviewer or anything, but you might want to add .idea/ and .DS_STORE to the .gitignore

Yes, I definitely forgot about it, thanks 😄

2022-06-03 23:35 UTC, TechStudent11 approved these changes
Very useful!

2022-06-04 05:17 UTC, jacesleeman requested changes

2022-06-04 05:17 UTC, jacesleeman commented on reddit/subreddit.py
> +    if os.getenv("THREAD_LINK"):
if os.getenv("THREAD_LINK"):

makes it look for THREAD_LINK in .env not THREAD

2022-06-04 05:17 UTC, jacesleeman commented on .env.template
> +THREAD=""
so this would need to be THREAD_LINK=""

2022-06-04 05:17 UTC, jacesleeman commented on reddit/subreddit.py
> +        thread_id = os.getenv("THREAD_LINK").split("/")[6]
or just make this and     if os.getenv("THREAD_LINK"): just say THREAD

2022-06-04 08:03 UTC, jacesleeman approved these changes

2022-06-04 16:48 UTC, EmreTech reviewed
I think it would be better if instead the user is prompted to input a link for a thread instead of keeping it in the env file.

2022-06-05 09:12 UTC, DomizianoScarcelli commented
> I think it would be better if instead the user is prompted to input a link for a thread instead of keeping it in the env file.

Yes maybe it has some more sense. I added a .env variable (RANDOM_THREAD) that accepts yes or no as values. If no (or empty) the script will ask the user for the link inside the terminal, otherwise the thread will be randomized.

2022-06-05 12:04 UTC, jacesleeman approved these changes

2022-06-05 12:16 UTC, DomizianoScarcelli commented
@CallumIO Hi, can I ask for a review to merge this PR?

2022-06-05 12:57 UTC, jacesleeman commented
make sure to edit the README checking off the thing

2022-06-05 18:07 UTC, EmreTech approved these changes

2022-06-05 18:07 UTC, elebumm commented
Looks great. Just removed the unused imports.

2022-06-05 18:07 UTC, elebumm approved these changes

2022-06-05 18:07 UTC, merged