Change from gTTS to tiktoks text to speech
elebumm/RedditVideoMakerBot pull request #305
Opened 2022-06-05 10:55 UTC by The-Drobe

Hello, I have added the ability to customize the voice. The end result is a much cleaner and nicer voice than gTTS text to speech.
### New Features
- Change the gender of the voice
- Multiple different voices to choose from
- Cleaner and less robotic voice

2022-06-05 13:16 UTC, supervoko approved these changes

2022-06-05 15:19 UTC, uberBuilder24 commented
Works like a charm! But are there more US Male voices? Thanks!

2022-06-05 16:27 UTC, The-Drobe commented
> Works like a charm! But are there more US Male voices? Thanks!

The voices that you can use are all listed [here](https://github.com/The-Drobe/RedditVideoMakerBot/blob/master/examples/ValidOptionsTTS.txt)

There is also this Twitter with voice samples but I have not tested if they work. [here](https://twitter.com/scanlime/status/1512598559769702406)

2022-06-05 20:37 UTC, noahcrum-dev commented
Hey, sorry I am rather new to github, how do I download this and use it? thank you for creating!

2022-06-05 20:56 UTC, nickshanks347 commented
+1 for this, works great

2022-06-06 00:34 UTC, MartinAlcalde commented on video_creation/voices.py
> +    if Voice == '':
You should add `or Voice is None` because reading and empty string returns None

2022-06-06 15:19 UTC, The-Drobe commented
> Could you add VoiceGender to main.py checks and setup.py?
> 
> Thanks!

Both have been done. When you mention VoiceGender I assume you mean the Voice variable.

2022-06-06 22:13 UTC, JasonLovesDoggo commented
> * Change the gender of the voice

If you are going to flat-out copy my code you could at least give me credit for it.

2022-06-07 00:10 UTC, The-Drobe commented
> > * Change the gender of the voice
> 
> If you are going to flat-out copy my code you could at least give me credit for it.

I referenced your code [here](https://github.com/The-Drobe/RedditVideoMakerBot/blob/master/video_creation/TTSwrapper.py#L3)

2022-06-07 01:34 UTC, JasonLovesDoggo commented
I'm sorry I didn't see that comment but yeah that's honestly fine. Sorry again.

2022-06-07 01:44 UTC, JasonLovesDoggo commented
> > > * Change the gender of the voice
> > 
> > If you are going to flat-out copy my code you could at least give me credit for it.
> 
> I referenced your code [here](https://github.com/The-Drobe/RedditVideoMakerBot/blob/master/video_creation/TTSwrapper.py#L3)   
> 
> Would you like to be referenced some where else as well?
> 
> It's also not exactly the same. If you wish to have more recognition I am a
> Happy to do that.

Oh also I updated that file to support unlimited text length so I would advise you to check that out

2022-06-07 05:12 UTC, The-Drobe commented
> > > > * Change the gender of the voice
> > > 
> > > 
> > > If you are going to flat-out copy my code you could at least give me credit for it.
> > 
> > 
> > I referenced your code [here](https://github.com/The-Drobe/RedditVideoMakerBot/blob/master/video_creation/TTSwrapper.py#L3)
> > Would you like to be referenced some where else as well?
> > It's also not exactly the same. If you wish to have more recognition I am a
> > Happy to do that.
> 
> Oh also I updated that file to support unlimited text length so I would advise you to check that out

I did implement that myself on this fork. It is implemented very differently from how you do it tho.

2022-06-07 13:16 UTC, BlockArchitech commented
Could you add VoiceGender to the checks in main.py and the setup.py assistant please?

2022-06-07 14:16 UTC, The-Drobe commented
> Could you add VoiceGender to the checks in main.py and the setup.py assistant please?

In my code, the variable name `VoiceGender` has not been used since [this commit](https://github.com/The-Drobe/RedditVideoMakerBot/commit/9ba7f40d11c3279cccb4490c1d23b724d5293083) in all newer commits I use the `Voice` varible to better suite what what the varible is used for.

2022-06-07 18:57 UTC, DrMxrcy commented
This branch has worked super well for me. Good work! Hopefully its implemented soon

2022-06-07 22:45 UTC, BlockArchitech commented
>  I use the Voice varible to better suite what what the varible is used for.


Awesome! As long as it makes it to the setup assistant.

2022-06-08 03:26 UTC, The-Drobe commented
> * Change the gender of the voice



> > I use the Voice varible to better suite what what the varible is used for.
> 
> Awesome! As long as it makes it to the setup assistant.

It was done in the following [commit](https://github.com/The-Drobe/RedditVideoMakerBot/commit/33f5f284ea177375ccc6daab1d4d88ea36104e4f#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R91)

2022-06-08 12:43 UTC, RobertSofronea commented
Has anyone encountered this error: "mutagen.mp3.HeaderNotFoundError: can't sync to MPEG frame" if so how did you solve it?

2022-06-08 21:32 UTC, BlockArchitech requested changes
Please download the *latest* setup.py from the develop branch. This setup.py is invalid.

Your pull request should be `BASE: develop HEAD: develop`

2022-06-09 02:16 UTC, The-Drobe commented
> Please download the *latest* setup.py from the develop branch. This setup.py is invalid.
> 
> Your pull request should be `BASE: develop HEAD: develop`

When I get the time I will. Rn in have to focus on assessments.

2022-06-09 13:27 UTC, DrMxrcy commented
Not using the Setup.py, but everything else seems to work great

2022-06-11 01:44 UTC, Auto-bos commented
Hey @The-Drobe I am a pretty new coder and decided to put your changes into the coding for this bot, but I get this error: "IndentationError: unindent does not match any outer indentation level"
Any help would be greatly appreciated!
![Untitled](https://user-images.githubusercontent.com/107288075/173167920-45edbe2b-356e-4b37-8e9b-dd82ea4403f5.png)

2022-06-11 02:33 UTC, JasonLovesDoggo commented
I am happy to help
Can you take a wider screenshot of your code?
@Auto-bos

2022-06-12 03:13 UTC, Auto-bos commented
> I am happy to help Can you take a wider screenshot of your code? @Auto-bos

I'm sorry I don't understand. That is all the text there is when I put "python main.py" into the command prompt of the folder

2022-06-12 07:51 UTC, Auto-bos commented
> I am happy to help Can you take a wider screenshot of your code? @Auto-bos

Actually, I don't need the help. I managed to troubleshoot the problems myself!
being a very novice coder I am super proud of myself.
Thanks for offering the help however.

2022-06-12 13:07 UTC, The-Drobe commented
I have changed the branch and updated the setup.py new pull request [here](https://github.com/elebumm/RedditVideoMakerBot/pull/467). I had to create a new pull request because you cant change the branch.

2022-06-12 13:08 UTC, closed without merging

2022-06-13 10:43 UTC, CrackedBrick commented
Any detailed guide? Sorry im new to coding, Github and stuff

2022-06-13 14:39 UTC, The-Drobe commented
> Any detailed guide? Sorry im new to coding, Github and stuff

What do you need help with?

2022-06-14 00:49 UTC, CrackedBrick commented
Changing the TTS voice, i just need a detailed guide how to change it

2022-06-15 04:13 UTC, The-Drobe commented
> Changing the TTS voice, i just need a detailed guide how to change it

- You can change it in the .env file. Vaild options here  https://github.com/The-Drobe/RedditVideoMakerBot/blob/master/examples/ValidOptionsTTS.txt