select the subreddit from the env file
elebumm/RedditVideoMakerBot pull request #5
Opened 2022-05-31 19:07 UTC by fabiand93

2022-05-31 19:29 UTC, SpaYco requested changes
hey @fabiand93, great work, I left some comments :)

2022-05-31 19:29 UTC, SpaYco commented on reddit/askreddit.py
> +    askreddit = reddit.subreddit(os.getenv("REDDIT_SUBREDDIT"))
let's keep `askreddit` as a default value

2022-05-31 19:29 UTC, SpaYco commented on README.md
> +4. Run `playwright install`
_I'm not familiar with Python so ignore this comment if it doesn't make sense_

Do we need to install this in order for the app to work? from looking at their page this is meant for testing, if this is optional then we should say that it is, and also explain what this does in a super short testing (ex: use this for testing)

2022-05-31 19:29 UTC, SpaYco commented on README.md
> +- [✅] Allowing users to choose between any subreddit.
out of the scope of this PR, but I think being able to pull from multiple subreddits at once would also be great! WDYT?

2022-06-02 18:13 UTC, elebumm commented
@fabiand93 Great PR! The last pr before this one did the same functionality, so sadly I have to close this one :( I think this is a great feature though.

2022-06-02 18:13 UTC, closed without merging