Restart/rerun the main.py script automatically
elebumm/RedditVideoMakerBot pull request #672
Opened 2022-06-23 18:40 UTC by hiccup-09

This will rerun or **re-execute the main.py script automatically** once it disrupted or killed by any error.

When I try to execute the main script multiple times by using **TIMES_TO_RUN="n"** feature sometimes the script stopped by some errors like timeout or sox not found, then I need to restart the script again and again so I wrote this to automate the restarting part if any error or timeout occures. if anyone wants to rerun the script for n number of times then they can by rewriting the while loop to run exactly n times.
and one more thing I found is that sometimes some specific reddit thread causes the errors (i don't know why) so try to put **RANDOM_THREAD="yes"** to yes so that it does loop on errors( like the script start -> found error -> got stopped -> restart by restart.py....and so on)

2022-06-24 21:17 UTC, CordlessCoder requested changes
This should really be implemented inside main.py, to catch those errors and retry running that function.
And this `restart.py` implementation doesn't integrate into the script in any way, and will only be confusing to people.

2022-06-25 03:11 UTC, LukeMedeiros916 approved these changes

2022-06-25 20:47 UTC, hiccup-09 commented
yes, many will be confused , but for me `restart.py` makes sure the main script will run for whole night if i want to even if it got any errors.

2022-06-27 20:25 UTC, closed without merging

2022-06-27 20:25 UTC, CordlessCoder commented
Unnecessary, bad implementation.